export const ACTION_TYPE = {
    SET_USER: "SET_USER",
    LOGOUT: "LOGOUT",
    SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
    SET_USER_DATA: "SET_USER_DATA",
    SET_COUNTER: "SET_COUNTER",
    SET_COUNTER_ERROR_FLAG: "SET_COUNTER_ERROR_FLAG",
    SET_NEW_QUANTITY: "SET_NEW_QUANTITY",
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    SET_TOTAL_PRODUCT_PLUS: "SET_TOTAL_PRODUCT_PLUS",
};
